# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.Browse = QtWidgets.QPushButton(self.groupBox_1)
        self.Browse.setMinimumSize(QtCore.QSize(120, 35))
        self.Browse.setObjectName("Browse")
        self.gridLayout_1.addWidget(self.Browse, 0, 0, 1, 1)
        self.ShowHistogram = QtWidgets.QPushButton(self.groupBox_1)
        self.ShowHistogram.setMinimumSize(QtCore.QSize(120, 35))
        self.ShowHistogram.setObjectName("ShowHistogram")
        self.gridLayout_1.addWidget(self.ShowHistogram, 1, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox_1)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_1.addWidget(self.label_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_1.addWidget(self.label_2, 0, 2, 1, 1)
        self.OriginalImg = QtWidgets.QWidget(self.groupBox_1)
        self.OriginalImg.setMinimumSize(QtCore.QSize(220, 180))
        self.OriginalImg.setObjectName("OriginalImg")
        self.verticalLayout_OriginalImg = QtWidgets.QVBoxLayout(self.OriginalImg)
        self.verticalLayout_OriginalImg.setObjectName("verticalLayout_OriginalImg")
        self.gridLayout_1.addWidget(self.OriginalImg, 1, 1, 2, 1)
        self.OriginalHist = QtWidgets.QWidget(self.groupBox_1)
        self.OriginalHist.setMinimumSize(QtCore.QSize(500, 180))
        self.OriginalHist.setObjectName("OriginalHist")
        self.verticalLayout_OriginalHist = QtWidgets.QVBoxLayout(self.OriginalHist)
        self.verticalLayout_OriginalHist.setObjectName("verticalLayout_OriginalHist")
        self.gridLayout_1.addWidget(self.OriginalHist, 1, 2, 2, 1)
        self.verticalLayout_main.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Apply = QtWidgets.QPushButton(self.groupBox_2)
        self.Apply.setMinimumSize(QtCore.QSize(120, 35))
        self.Apply.setObjectName("Apply")
        self.gridLayout_2.addWidget(self.Apply, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.EqualizedImg = QtWidgets.QWidget(self.groupBox_2)
        self.EqualizedImg.setMinimumSize(QtCore.QSize(220, 180))
        self.EqualizedImg.setObjectName("EqualizedImg")
        self.verticalLayout_EqualizedImg = QtWidgets.QVBoxLayout(self.EqualizedImg)
        self.verticalLayout_EqualizedImg.setObjectName("verticalLayout_EqualizedImg")
        self.gridLayout_2.addWidget(self.EqualizedImg, 1, 1, 1, 1)
        self.EqualizedHist = QtWidgets.QWidget(self.groupBox_2)
        self.EqualizedHist.setMinimumSize(QtCore.QSize(500, 180))
        self.EqualizedHist.setObjectName("EqualizedHist")
        self.verticalLayout_EqualizedHist = QtWidgets.QVBoxLayout(self.EqualizedHist)
        self.verticalLayout_EqualizedHist.setObjectName("verticalLayout_EqualizedHist")
        self.gridLayout_2.addWidget(self.EqualizedHist, 1, 2, 1, 1)
        self.verticalLayout_main.addWidget(self.groupBox_2)
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BinaryThreshold = QtWidgets.QRadioButton(self.groupBox_3)
        self.BinaryThreshold.setObjectName("BinaryThreshold")
        self.gridLayout_3.addWidget(self.BinaryThreshold, 0, 0, 1, 1)
        self.OtsuThreshold = QtWidgets.QRadioButton(self.groupBox_3)
        self.OtsuThreshold.setObjectName("OtsuThreshold")
        self.gridLayout_3.addWidget(self.OtsuThreshold, 1, 0, 1, 1)
        self.Validate_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.Validate_1.setMinimumSize(QtCore.QSize(100, 35))
        self.Validate_1.setObjectName("Validate_1")
        self.gridLayout_3.addWidget(self.Validate_1, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.ThresholdingImg = QtWidgets.QWidget(self.groupBox_3)
        self.ThresholdingImg.setMinimumSize(QtCore.QSize(180, 180))
        self.ThresholdingImg.setObjectName("ThresholdingImg")
        self.verticalLayout_ThresholdingImg = QtWidgets.QVBoxLayout(self.ThresholdingImg)
        self.verticalLayout_ThresholdingImg.setObjectName("verticalLayout_ThresholdingImg")
        self.gridLayout_3.addWidget(self.ThresholdingImg, 1, 1, 2, 1)
        self.horizontalLayout_bottom.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.GaussianFilter = QtWidgets.QRadioButton(self.groupBox_4)
        self.GaussianFilter.setObjectName("GaussianFilter")
        self.gridLayout_4.addWidget(self.GaussianFilter, 0, 0, 1, 1)
        self.MeanFilter = QtWidgets.QRadioButton(self.groupBox_4)
        self.MeanFilter.setObjectName("MeanFilter")
        self.gridLayout_4.addWidget(self.MeanFilter, 1, 0, 1, 1)
        self.MedianFilter = QtWidgets.QRadioButton(self.groupBox_4)
        self.MedianFilter.setObjectName("MedianFilter")
        self.gridLayout_4.addWidget(self.MedianFilter, 2, 0, 1, 1)
        self.Validate_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.Validate_2.setMinimumSize(QtCore.QSize(100, 35))
        self.Validate_2.setObjectName("Validate_2")
        self.gridLayout_4.addWidget(self.Validate_2, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 1, 1, 1)
        self.FilteredImg = QtWidgets.QWidget(self.groupBox_4)
        self.FilteredImg.setMinimumSize(QtCore.QSize(180, 180))
        self.FilteredImg.setObjectName("FilteredImg")
        self.verticalLayout_FilteredImg = QtWidgets.QVBoxLayout(self.FilteredImg)
        self.verticalLayout_FilteredImg.setObjectName("verticalLayout_FilteredImg")
        self.gridLayout_4.addWidget(self.FilteredImg, 1, 1, 3, 1)
        self.horizontalLayout_bottom.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Rotation = QtWidgets.QRadioButton(self.groupBox_5)
        self.Rotation.setObjectName("Rotation")
        self.gridLayout_5.addWidget(self.Rotation, 0, 0, 1, 1)
        self.Extraction = QtWidgets.QRadioButton(self.groupBox_5)
        self.Extraction.setObjectName("Extraction")
        self.gridLayout_5.addWidget(self.Extraction, 1, 0, 1, 1)
        self.Agrandissement = QtWidgets.QRadioButton(self.groupBox_5)
        self.Agrandissement.setObjectName("Agrandissement")
        self.gridLayout_5.addWidget(self.Agrandissement, 2, 0, 1, 1)
        self.Validate_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Validate_3.setMinimumSize(QtCore.QSize(100, 35))
        self.Validate_3.setObjectName("Validate_3")
        self.gridLayout_5.addWidget(self.Validate_3, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.AugmentedImg = QtWidgets.QWidget(self.groupBox_5)
        self.AugmentedImg.setMinimumSize(QtCore.QSize(180, 180))
        self.AugmentedImg.setObjectName("AugmentedImg")
        self.verticalLayout_AugmentedImg = QtWidgets.QVBoxLayout(self.AugmentedImg)
        self.verticalLayout_AugmentedImg.setObjectName("verticalLayout_AugmentedImg")
        self.gridLayout_5.addWidget(self.AugmentedImg, 1, 1, 3, 1)
        self.horizontalLayout_bottom.addWidget(self.groupBox_5)
        self.verticalLayout_main.addLayout(self.horizontalLayout_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Image Originale"))
        self.Browse.setText(_translate("MainWindow", "Parcourir"))
        self.ShowHistogram.setText(_translate("MainWindow", "Afficher Histogramme"))
        self.label_1.setText(_translate("MainWindow", "Image Originale"))
        self.label_2.setText(_translate("MainWindow", "Histogramme de l'image originale"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Égalisation d'histogramme"))
        self.Apply.setText(_translate("MainWindow", "Appliquer"))
        self.label_3.setText(_translate("MainWindow", "Image Égalisée"))
        self.label_4.setText(_translate("MainWindow", "Histogramme de l'image égalisée"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Seuillage"))
        self.BinaryThreshold.setText(_translate("MainWindow", "Seuillage binaire"))
        self.OtsuThreshold.setText(_translate("MainWindow", "Seuillage d'Otsu"))
        self.Validate_1.setText(_translate("MainWindow", "Valider"))
        self.label_5.setText(_translate("MainWindow", "Image Seuillée"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Filtrage"))
        self.GaussianFilter.setText(_translate("MainWindow", "Filtre Gaussien"))
        self.MeanFilter.setText(_translate("MainWindow", "Filtre moyenneur"))
        self.MedianFilter.setText(_translate("MainWindow", "Filtre médian"))
        self.Validate_2.setText(_translate("MainWindow", "Valider"))
        self.label_6.setText(_translate("MainWindow", "Image Filtrée"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Opérations géométriques"))
        self.Rotation.setText(_translate("MainWindow", "Rotation"))
        self.Extraction.setText(_translate("MainWindow", "Extraction"))
        self.Agrandissement.setText(_translate("MainWindow", "Agrandissement"))
        self.Validate_3.setText(_translate("MainWindow", "Valider"))
        self.label_7.setText(_translate("MainWindow", "Image Augmentée"))